### ISSUE TITLE
Change lazy implementation

### ISSUE THREAD

**Issue by cmccomb** [cmccomb/human_regex#2]
The current implementation of `lazy()` as a method of `HumanRegex` has potential for misuse - adding lazy modifier in places that don't make sense, potentially leading to undefined behavior. This should updated to include direct functions that do lazy repetitions (i.e., `lazy_one_or_more(target)`) to ensure defined behavior.

**Comment by cmccomb** [comment]
@PacificBird what are your thoughts on this?

**Comment by PacificBird** [comment]
I'll have to look into it further, if I remember correctly I updated `lazy()` to take any `HumanRegex<T>` instead of specifying some parameters, though I'm unsure if the type system would be enough to protect from misuse. If it _is_ enough we can just update the genetic parameters, but if it isn't I agree on including direct functions to avoid accidental misuse.
